[common]
seed = 42

[generate_data]
num_users = 2000
num_items = 2000
steps = 100
output_dir = "dataset"

[process_dataset]
input_file = "dataset/data_2000_2000_100.csv"
output_dir = "preprocessed_dataset"

[train.gru4rec]
output_dir = "trained_models/gru4rec"
epochs = 10
batch_size = 256
embedding_dim = 64
hidden_size = 128
dropout = 0.1
lr = 0.001



[evaluate]
gru4rec_path = "trained_models/gru4rec"
num_episodes = 100
drift_scale = 0.1
seed = 42
alpha = 0.1
output_dir = "evaluation_report"
